Represents one of the outputs of an Operation.

In [1]:
import tensorflow as tf
import numpy as np

## Numpy <-> Tensor

In [2]:
np_arr = np.array([1, 2, 3], dtype=np.int32)

tf.convert_to_tensor(np_arr)

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [3]:
t = tf.random.uniform((3, 1))

t.numpy()

array([[0.32156897],
       [0.617237  ],
       [0.13312566]], dtype=float32)

In [4]:
a = tf.constant([1, 2, 3], dtype='int64')

a

<tf.Tensor: id=10, shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [5]:
a = np.random.randn(5)

b = tf.ones(5)
print(a)
print(b)
print(a + b)

[ 1.05618404 -1.38271462 -0.27925556  0.63304793  1.28361572]
tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32)
tf.Tensor([ 2.056184   -0.38271463  0.72074443  1.6330479   2.2836156 ], shape=(5,), dtype=float32)


In [6]:
tf.fill((2, 4), np.pi)

<tf.Tensor: id=21, shape=(2, 4), dtype=float32, numpy=
array([[3.1415927, 3.1415927, 3.1415927, 3.1415927],
       [3.1415927, 3.1415927, 3.1415927, 3.1415927]], dtype=float32)>

In [7]:
a = np.array([1, 2, 3])
print(tf.is_tensor(a))

b = tf.constant([1, 2, 3])
print(tf.is_tensor(b))

False
True


## ones and ones_like, zeros and zeros_lie

In [8]:
print(tf.ones((1, 3), dtype='int32'))


a = np.array([1, 2, 3, 4])
print(tf.ones_like(a))

print(tf.zeros_like(a))

tf.Tensor([[1 1 1]], shape=(1, 3), dtype=int32)
tf.Tensor([1 1 1 1], shape=(4,), dtype=int64)
tf.Tensor([0 0 0 0], shape=(4,), dtype=int64)


## size and shape

In [9]:

a = tf.random.uniform((4, 3))

print(a.get_shape())
print(a.shape)

print(tf.size(a))

(4, 3)
(4, 3)
tf.Tensor(12, shape=(), dtype=int32)


## Reshape

In [10]:
a = tf.random.uniform((5, 20))

b = tf.reshape(a, (10, 10))
print(b.shape)

c = tf.reshape(a, (10, -1))
print(c.shape)

d = tf.reshape(a, (1, -1, 4))
print(d.shape)

e = tf.reshape(a, (-1,))
print(e.shape)

(10, 10)
(10, 10)
(1, 25, 4)
(100,)


## Type-casting

In [11]:

a = np.array([1, 2, 3])
print(tf.cast(a, tf.int64), '\n')

b = tf.random.uniform((2,))
print('Orig  ::  ', b)
print('After ::  ', tf.cast(b, tf.float64), '\n')

c = tf.constant([1, 2])
print('Orig  ::  ', c)
print('After ::  ', tf.cast(c, tf.int64))

tf.Tensor([1 2 3], shape=(3,), dtype=int64) 

Orig  ::   tf.Tensor([0.98031855 0.6233758 ], shape=(2,), dtype=float32)
After ::   tf.Tensor([0.98031855 0.62337577], shape=(2,), dtype=float64) 

Orig  ::   tf.Tensor([1 2], shape=(2,), dtype=int32)
After ::   tf.Tensor([1 2], shape=(2,), dtype=int64)


## rank

In [12]:
a = np.random.randn(3, 4, 4, 7)

print(tf.rank(a))

tf.Tensor(4, shape=(), dtype=int32)


## one-hot 

In [13]:
tf.one_hot(
    indices = [2, 0, 1, 3, 2, 1, 3, 0],
    depth=4)


<tf.Tensor: id=83, shape=(8, 4), dtype=float32, numpy=
array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]], dtype=float32)>

## Padding

In [14]:
a = tf.constant([[9.0, 8.0, 7.0], [4.0, 3.0, 4.0]])
print(a)

p = tf.constant([[0, 1], [2, 3]])
print(p.shape)
## the first dimension of `p` corresponds to each dimension of `a`
## p[:, 0] ==> how many values to add before the specified dimension
## p[:, 1] ==> how many values to add after the specified dimension

tf.pad(a, p, 'constant')

tf.Tensor(
[[9. 8. 7.]
 [4. 3. 4.]], shape=(2, 3), dtype=float32)
(2, 2)


<tf.Tensor: id=88, shape=(3, 8), dtype=float32, numpy=
array([[0., 0., 9., 8., 7., 0., 0., 0.],
       [0., 0., 4., 3., 4., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [15]:
c = tf.eye(3)
c

<tf.Tensor: id=93, shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

## split

In [16]:
a = tf.random.uniform((4, 16))

a1, a2, a3 = tf.split(a, num_or_size_splits=[4, 5, 7], axis=1)

print('a1: ', a1.shape)
print('a2: ', a2.shape)
print('a3: ', a3.shape)

a1:  (4, 4)
a2:  (4, 5)
a3:  (4, 7)


## squeeze

In [17]:
a = tf.random.uniform((1, 2, 1, 4))
print(a.shape)

a = tf.squeeze(a)
print(a.shape)

(1, 2, 1, 4)
(2, 4)


## stack

In [18]:
a1 = tf.random.uniform((4, 5))
a2 = tf.random.uniform((4, 5))
a3 = tf.random.uniform((4, 5))

print('axis=0 ==> ', tf.stack((a1, a2, a3), axis=0).shape)

print('axis=1 ==> ', tf.stack((a1, a2, a3), axis=1).shape)


axis=0 ==>  (3, 4, 5)
axis=1 ==>  (4, 3, 5)


## Reverse

In [19]:
a = np.arange(9)
a = tf.reshape(a, (3, 3))
print(a)

a_rev0 = tf.reverse(a, axis=(0,))
print(a_rev0)

a_rev1 = tf.reverse(a, axis=(1,))
print(a_rev1)

a_rev2 = tf.reverse(a, axis=(0, 1))
print(a_rev2)


tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int64)
tf.Tensor(
[[6 7 8]
 [3 4 5]
 [0 1 2]], shape=(3, 3), dtype=int64)
tf.Tensor(
[[2 1 0]
 [5 4 3]
 [8 7 6]], shape=(3, 3), dtype=int64)
tf.Tensor(
[[8 7 6]
 [5 4 3]
 [2 1 0]], shape=(3, 3), dtype=int64)


## Gradients

In [20]:

xs = tf.random.uniform((3, 4))

with tf.GradientTape() as g:
    g.watch(xs)
    ys = xs * xs
#
g.gradient(ys, xs)

<tf.Tensor: id=164, shape=(3, 4), dtype=float32, numpy=
array([[0.64276767, 0.34620285, 1.8753572 , 0.5555122 ],
       [1.7459497 , 0.5125499 , 1.6727219 , 1.3211439 ],
       [1.3780808 , 1.4605448 , 0.8230636 , 1.5085907 ]], dtype=float32)>